FROM mcr.microsoft.com/devcontainers/go:1.20-bullseye
CMD sudo apt update && sudo apt install -y gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev
ENV DISPLAY=host.docker.internal:0